# -*- coding: utf-8 -*-
"""DFA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y-JPEBQnyUurwUbCejoTZBeRB2aKErW1
"""

# Deterministic Finite Automata (DFA) implementation in python using class and objects by passing strings from dictionary
class DFA(object):
      #initialize all variable when calling the class DFA
    def __init__(self, states,input_variable , transition, initial_state,final_states):
        self.states = states;
        self.input_variable = input_variable;
        self.transition = transition;
        self.initial_state = initial_state;
        self.final_states = final_states;
        return;
    def Det_finite_Auto(self,input_string):
      states ='q0'
      for i in input_string:
        if states=='q0':
          if i=='a':
            states='q1'
          elif i=='b':
            states='q0'
          else:
            return False
        elif states=='q1':
          if i=='a':
            states='q1'
          elif i=='b':
            states='q2'
          else:
            return False
        elif states=='q2':
          if i=='a':
            states='q1'
          elif i=='b':
            states='q2'
            return True
          else:
             return False

    #   if states in final_states:
    #     return True
    #   else:
    #     return False


dfa1 = DFA(
    input_variable=['a','b'],
    states=['q0','q1','q2'],
    transition={('q0','a'):'q1',('q0','b'):'q0',('q1','a'):'q1',('q1','b'):'q2',('q2','a'):'q1',('q2','b'):'q2'},
    initial_state='q0',
    final_states='q2')    

if __name__ == "__main__" :
  string={0:'ababab',
          1:'abababb',
          2:'ababba',
          3:'bababa',
          4:'aabbab',
          5:'babbb',
          6:'aabaab'}
for i in string:
  if(dfa1.Det_finite_Auto(string[i])):

        print(string[i],"->","is ACCEPTED")
  else:  
        print(string[i],"->"," is REJECTED")